name: "Dev Deploy"

# Gatilho — roda quando fizer push na branch 'develop'.
on:
  push:
    branches:
      - develop

permissions:         # Permissões do token de acesso do GitHub
  id-token: write
  contents: read

# Jobs — define as etapas do workflow que serão executadas.
jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml          # Reutiliza o workflow terraform.yml
    with:     # Passar parâmetros para o workflow reutilizável
      environment: "dev"
      aws-region: ${{ secrets.AWS_REGION }}
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_STATEFILE_S3_BUCKET: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      AWS_LOCK_DYNAMODB_TABLE: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
